library(ggplot2)
library(magrittr)
library(ggpubr)
library(ggfortify)
library(cluster)
library(scatterplot3d)
View(getwd())
#setwd("C:/Users/91809/Desktop/OMICS World/bioinformatics-master") 
input_file <- "CellLines_ExprData_marked.txt"
View(input_file)
full_table1 <- read.table (input_file, header = TRUE)
View(full_table)
expressions = as.matrix(full_table[2:nrow(full_table), 2:ncol(full_table)])
autoplot(prcomp(t(expressions)))
autoplot(prcomp(t(expressions)), label = TRUE, label.size = 8, colour = "red")
autoplot(prcomp(t(expressions)), loadings = TRUE, label = TRUE, shape = FALSE, label.size = 2)
View(expressions)
